/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
 * Generated on: 01-May-2020 09:56:43
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,14 -> [-2 2)
 * Denominator         : s16,14 -> [-2 2)
 * Scale Values        : s16,15 -> [-1 1)
 * Input               : s16,15 -> [-1 1)
 * Section Input       : s16,10 -> [-32 32)
 * Section Output      : s16,11 -> [-16 16)
 * Output              : s16,11 -> [-16 16)
 * State               : s16,15 -> [-1 1)
 * Numerator Prod      : s32,29 -> [-4 4)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s40,29 -> [-1024 1024)
 * Denominator Accum   : s40,29 -> [-1024 1024)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 * Cast Before Sum     : true
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 9
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const int16_T NUM[MWSPT_NSEC][3] = {
  {
    11907,      0,      0 
  },
  {
    16384, -10697,  16384 
  },
  {
     9509,      0,      0 
  },
  {
    16384, -15246,  16384 
  },
  {
     7710,      0,      0 
  },
  {
    16384, -23586,  16384 
  },
  {
     6678,      0,      0 
  },
  {
    16384, -31477,  16384 
  },
  {
    16384,      0,      0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const int16_T DEN[MWSPT_NSEC][3] = {
  {
    16384,      0,      0 
  },
  {
    16384,  -2412,  12793 
  },
  {
    16384,      0,      0 
  },
  {
    16384,  -4117,   7363 
  },
  {
    16384,      0,      0 
  },
  {
    16384,  -6597,   3537 
  },
  {
    16384,      0,      0 
  },
  {
    16384,  -8385,   1418 
  },
  {
    16384,      0,      0 
  }
};
