/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
 * Generated on: 28-Apr-2020 10:00:19
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,14 -> [-2 2)
 * Denominator         : s16,14 -> [-2 2)
 * Scale Values        : s16,15 -> [-1 1)
 * Input               : s16,15 -> [-1 1)
 * Section Input       : s16,10 -> [-32 32)
 * Section Output      : s16,11 -> [-16 16)
 * Output              : s16,11 -> [-16 16)
 * State               : s16,15 -> [-1 1)
 * Numerator Prod      : s32,29 -> [-4 4)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s40,29 -> [-1024 1024)
 * Denominator Accum   : s40,29 -> [-1024 1024)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 * Cast Before Sum     : true
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,2,1 };
const int16_T NUM[MWSPT_NSEC][3] = {
  {
    16109,      0,      0 
  },
  {
    16384, -32700,  16384 
  },
  {
    15669,      0,      0 
  },
  {
    16384, -32715,  16384 
  },
  {
    15328,      0,      0 
  },
  {
    16384, -32739,  16384 
  },
  {
    15113,      0,      0 
  },
  {
    16384, -32760,  16384 
  },
  {
    15698,      0,      0 
  },
  {
    16384, -16384,      0 
  },
  {
    16384,      0,      0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,2,1 };
const int16_T DEN[MWSPT_NSEC][3] = {
  {
    16384,      0,      0 
  },
  {
    16384, -32089,  15895 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -31228,  15014 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -30570,  14330 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -30160,  13899 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -15011,      0 
  },
  {
    16384,      0,      0 
  }
};
